-- PintService - schema preparado para uso futuro
-- Não é necessário para publicar o site na Vercel em modo demonstração.
-- O acesso do app em produção é feito apenas no servidor com SUPABASE_SECRET_KEY.
-- Todas as tabelas públicas usam RLS sem políticas públicas por padrão.

create table if not exists public.clientes (
  id uuid primary key default gen_random_uuid(),
  nome text,
  telefone text not null unique,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create table if not exists public.veiculos (
  id uuid primary key default gen_random_uuid(),
  cliente_id uuid references public.clientes(id) on delete cascade,
  placa text not null unique,
  modelo text,
  cor text,
  status text,
  setor text,
  observacoes text,
  ultima_atualizacao timestamptz not null default now(),
  criado_em timestamptz not null default now()
);

create table if not exists public.conversas (
  id bigint generated by default as identity primary key,
  telefone text not null,
  cliente_id uuid references public.clientes(id) on delete set null,
  veiculo_id uuid references public.veiculos(id) on delete set null,
  message_id text unique,
  mensagem text not null,
  origem text not null check (origem in ('cliente','bot','humano','sistema')),
  intencao text,
  tipo_mensagem text not null default 'text',
  media_id text,
  atendente_assumiu boolean not null default false,
  criado_em timestamptz not null default now()
);

create table if not exists public.estado_atendimento (
  telefone text primary key,
  etapa text not null default 'inicio',
  bot_ativo boolean not null default true,
  ultima_intencao text,
  placa_contexto text,
  aguardando_campo text,
  atualizado_em timestamptz not null default now()
);

create table if not exists public.pendencias (
  id uuid primary key default gen_random_uuid(),
  cliente_id uuid references public.clientes(id) on delete cascade,
  veiculo_id uuid references public.veiculos(id) on delete set null,
  tipo text not null,
  mensagem text,
  prioridade text not null default 'normal' check (prioridade in ('baixa','normal','alta','urgente')),
  status text not null default 'aberta' check (status in ('aberta','em_atendimento','concluida','cancelada')),
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create table if not exists public.funcionarios (
  id uuid primary key default gen_random_uuid(),
  nome text not null,
  setor text not null,
  telefone text,
  cargo text,
  ativo boolean not null default true,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create table if not exists public.tarefas_operacionais (
  id uuid primary key default gen_random_uuid(),
  codigo text not null default upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 10)),
  cliente_id uuid references public.clientes(id) on delete cascade,
  veiculo_id uuid references public.veiculos(id) on delete cascade,
  telefone_cliente text not null,
  tipo text not null check (tipo in ('confirmar_etapa','tirar_foto','confirmar_peca','verificar_status_fisico','informacao_setor')),
  titulo text not null,
  instrucoes text not null,
  setor_responsavel text,
  responsavel_id uuid references public.funcionarios(id) on delete set null,
  prioridade text not null default 'normal' check (prioridade in ('baixa','normal','alta','urgente')),
  status text not null default 'aberta' check (status in ('aberta','em_execucao','aguardando_confirmacao','resolvida','cancelada')),
  requer_foto boolean not null default false,
  resposta_funcionario text,
  evidencia_url text,
  evidencia_media_id text,
  resultado jsonb not null default '{}'::jsonb,
  dedupe_key text not null,
  origem_mensagem text,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),
  resolvido_em timestamptz
);

alter table public.tarefas_operacionais add column if not exists codigo text;
alter table public.tarefas_operacionais alter column codigo set default upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 10));
update public.tarefas_operacionais set codigo = upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 10)) where codigo is null;
alter table public.tarefas_operacionais alter column codigo set not null;
alter table public.tarefas_operacionais add column if not exists evidencia_media_id text;

create table if not exists public.tarefa_eventos (
  id bigint generated by default as identity primary key,
  tarefa_id uuid not null references public.tarefas_operacionais(id) on delete cascade,
  ator_tipo text not null check (ator_tipo in ('ia','funcionario','sistema')),
  ator_id uuid,
  evento text not null,
  dados jsonb not null default '{}'::jsonb,
  criado_em timestamptz not null default now()
);

create table if not exists public.tarefa_mensagens_whatsapp (
  id bigint generated by default as identity primary key,
  tarefa_id uuid not null references public.tarefas_operacionais(id) on delete cascade,
  funcionario_id uuid not null references public.funcionarios(id) on delete cascade,
  message_id text not null unique,
  direcao text not null check (direcao in ('sistema_para_funcionario','funcionario_para_sistema')),
  finalidade text not null check (finalidade in ('solicitacao','confirmacao','ambiguidade')),
  criado_em timestamptz not null default now()
);

alter table public.estado_atendimento add column if not exists tarefa_aguardada_id uuid references public.tarefas_operacionais(id) on delete set null;

create table if not exists public.decisoes_ia (
  id bigint generated by default as identity primary key,
  telefone text not null,
  mensagem text,
  intencao text,
  acao text,
  confianca numeric(5,4),
  prioridade text,
  precisa_atendente boolean not null default false,
  dados jsonb not null default '{}'::jsonb,
  criado_em timestamptz not null default now()
);

create table if not exists public.eventos_whatsapp (
  message_id text primary key,
  telefone text not null,
  recebido_em timestamptz not null default now()
);

create index if not exists idx_veiculos_cliente on public.veiculos(cliente_id);
create index if not exists idx_veiculos_placa_upper on public.veiculos((upper(placa)));
create index if not exists idx_conversas_telefone_id on public.conversas(telefone, id desc);
create index if not exists idx_conversas_cliente on public.conversas(cliente_id, criado_em desc);
create index if not exists idx_pendencias_status_prioridade on public.pendencias(status, prioridade, criado_em);
create index if not exists idx_pendencias_cliente on public.pendencias(cliente_id);
create index if not exists idx_funcionarios_setor_ativo on public.funcionarios(setor, ativo);
create unique index if not exists uq_funcionarios_telefone on public.funcionarios(telefone) where telefone is not null;
create unique index if not exists uq_tarefas_operacionais_codigo on public.tarefas_operacionais(codigo);
create index if not exists idx_tarefas_operacionais_fila on public.tarefas_operacionais(status, setor_responsavel, prioridade, criado_em);
create index if not exists idx_tarefas_operacionais_responsavel on public.tarefas_operacionais(responsavel_id, status, criado_em desc);
create index if not exists idx_tarefas_operacionais_veiculo on public.tarefas_operacionais(veiculo_id, status, criado_em desc);
create index if not exists idx_tarefa_eventos_tarefa on public.tarefa_eventos(tarefa_id, criado_em);
create index if not exists idx_tarefa_mensagens_tarefa on public.tarefa_mensagens_whatsapp(tarefa_id, criado_em desc);
create unique index if not exists uq_tarefa_operacional_ativa_dedupe on public.tarefas_operacionais(dedupe_key) where status in ('aberta','em_execucao','aguardando_confirmacao');
create index if not exists idx_decisoes_ia_telefone on public.decisoes_ia(telefone, criado_em desc);

alter table public.clientes enable row level security;
alter table public.veiculos enable row level security;
alter table public.conversas enable row level security;
alter table public.estado_atendimento enable row level security;
alter table public.pendencias enable row level security;
alter table public.funcionarios enable row level security;
alter table public.tarefas_operacionais enable row level security;
alter table public.tarefa_eventos enable row level security;
alter table public.tarefa_mensagens_whatsapp enable row level security;
alter table public.decisoes_ia enable row level security;
alter table public.eventos_whatsapp enable row level security;

-- Sem policies públicas: anon/authenticated não acessam estas tabelas diretamente.
