import 'server-only';
import { resolveOperationalTask } from '@/lib/operational-tasks';
import { findTaskIdByOutboundMessage, sendMappedTaskText } from '@/lib/task-messaging';
import { getSupabaseAdmin } from '@/lib/supabase-server';
import { normalizeWhatsAppPhone, sendWhatsAppText, type IncomingWhatsAppMessage } from '@/lib/whatsapp';

const ACTIVE_TASK_STATUSES = ['aberta', 'em_execucao', 'aguardando_confirmacao'];
const TASK_CODE_PATTERN = /#[A-Z0-9]{10}\b/gi;
type Employee = { id: string; nome: string; setor: string | null; telefone: string | null; cargo: string | null };
type LocatedTask = { task: any | null; purpose: string | null; ambiguousIds: string[] };
function relationOne<T = any>(value: T | T[] | null | undefined): T | null { if (Array.isArray(value)) return value[0] ?? null; return value ?? null; }
function normalizeText(value = '') { return value.normalize('NFD').replace(/[\u0300-\u036f]/g, '').trim().toLowerCase(); }
function isPositiveConfirmation(value: string) { const normalized = normalizeText(value).replace(/[.!]+$/g, ''); return ['sim', 's', 'sim pode enviar', 'sim, pode enviar', 'confirmo'].includes(normalized); }
function isNegativeConfirmation(value: string) { const normalized = normalizeText(value).replace(/[.!]+$/g, ''); return ['nao', 'n', 'nao enviar', 'nao, corrigir', 'corrigir'].includes(normalized); }
function extractTaskCode(value = '') { const match = value.toUpperCase().match(/#([A-Z0-9]{10})\b/); return match?.[1] ?? ''; }
function stripTaskCode(value = '') { return value.replace(TASK_CODE_PATTERN, '').replace(/\s{2,}/g, ' ').trim(); }
async function getTask(taskId: string) { const supabase = getSupabaseAdmin(); const { data, error } = await supabase.from('tarefas_operacionais').select('id,codigo,cliente_id,veiculo_id,telefone_cliente,tipo,titulo,instrucoes,setor_responsavel,responsavel_id,prioridade,status,requer_foto,resposta_funcionario,evidencia_url,evidencia_media_id,origem_mensagem,veiculos(id,placa,modelo,status,setor)').eq('id', taskId).maybeSingle(); if (error) throw error; return data ?? null; }
async function findTaskForEmployee(message: IncomingWhatsAppMessage, employee: Employee): Promise<LocatedTask> {
  const supabase = getSupabaseAdmin();
  if (message.contextMessageId) { const mapping = await findTaskIdByOutboundMessage(message.contextMessageId); if (mapping?.tarefa_id && mapping.funcionario_id === employee.id) return { task: await getTask(mapping.tarefa_id), purpose: mapping.finalidade as string | null, ambiguousIds: [] }; }
  const code = extractTaskCode(`${message.text} ${message.interactiveId}`); if (code) { const { data, error } = await supabase.from('tarefas_operacionais').select('id').eq('codigo', code).in('status', ACTIVE_TASK_STATUSES).maybeSingle(); if (error) throw error; if (data?.id) return { task: await getTask(data.id), purpose: null, ambiguousIds: [] }; }
  const { data: assigned, error } = await supabase.from('tarefas_operacionais').select('id').eq('responsavel_id', employee.id).in('status', ACTIVE_TASK_STATUSES).order('criado_em', { ascending: false }).limit(6); if (error) throw error; if (assigned?.length === 1) return { task: await getTask(assigned[0].id), purpose: null, ambiguousIds: [] };
  return { task: null, purpose: null, ambiguousIds: (assigned ?? []).map((item: any) => item.id) };
}
async function sendAmbiguityMessage(employee: Employee, taskIds: string[]) {
  const supabase = getSupabaseAdmin(); if (!employee.telefone) return;
  if (!taskIds.length) { await sendWhatsAppText(employee.telefone, 'Não encontrei nenhuma tarefa operacional aberta atribuída a você. Se você recebeu uma tarefa antes, responda diretamente àquela mensagem para eu identificar corretamente.'); return; }
  const { data: tasks, error } = await supabase.from('tarefas_operacionais').select('id,codigo,titulo,veiculos(placa,modelo)').in('id', taskIds); if (error) throw error;
  const lines = (tasks ?? []).map((task: any) => { const vehicle = relationOne<any>(task.veiculos); const label = vehicle?.modelo ? `${vehicle.modelo} ${vehicle.placa}` : vehicle?.placa ?? 'veículo'; return `#${task.codigo} — ${label} — ${task.titulo}`; });
  await sendWhatsAppText(employee.telefone, ['Tenho mais de uma tarefa sua aberta e não quero adivinhar de qual veículo é essa resposta.', '', ...lines, '', 'Envie novamente a informação/foto colocando o código no texto ou na legenda, por exemplo: #A1B2C3D4E5.', 'Outra opção é responder diretamente à mensagem original da tarefa.'].join('\n'));
}
async function ensureTaskBelongsToEmployee(task: any, employee: Employee) { if (!task) return false; if (!task.responsavel_id) { const supabase = getSupabaseAdmin(); const { error } = await supabase.from('tarefas_operacionais').update({ responsavel_id: employee.id, atualizado_em: new Date().toISOString() }).eq('id', task.id); if (error) throw error; task.responsavel_id = employee.id; return true; } return task.responsavel_id === employee.id; }
async function requestCorrection(task: any, employee: Employee, contextMessageId: string) { const supabase = getSupabaseAdmin(); const { error } = await supabase.from('tarefas_operacionais').update({ status: 'em_execucao', resposta_funcionario: null, evidencia_url: null, evidencia_media_id: null, atualizado_em: new Date().toISOString() }).eq('id', task.id); if (error) throw error; await supabase.from('tarefa_eventos').insert({ tarefa_id: task.id, ator_tipo: 'funcionario', ator_id: employee.id, evento: 'confirmacao_recusada', dados: {} }); if (employee.telefone) await sendMappedTaskText({ taskId: task.id, employeeId: employee.id, employeePhone: employee.telefone, text: `Sem problema. Envie a informação correta${task.requer_foto ? ' e a foto correta' : ''} respondendo esta mensagem. Tarefa #${task.codigo}.`, purpose: 'solicitacao', contextMessageId }); }
async function confirmStagedTask(task: any, employee: Employee, message: IncomingWhatsAppMessage) {
  if (!employee.telefone) return { ok: false }; const confirmationText = stripTaskCode(message.text);
  if (isNegativeConfirmation(confirmationText)) { await requestCorrection(task, employee, message.id); return { ok: true, corrected: true }; }
  if (!isPositiveConfirmation(confirmationText)) { await sendMappedTaskText({ taskId: task.id, employeeId: employee.id, employeePhone: employee.telefone, text: `Para evitar enviar algo errado ao cliente, responda somente SIM para confirmar ou NÃO para corrigir. Tarefa #${task.codigo}.`, purpose: 'confirmacao', contextMessageId: message.id }); return { ok: true, waitingConfirmation: true }; }
  if (!task.resposta_funcionario?.trim()) { await requestCorrection(task, employee, message.id); return { ok: true, corrected: true }; }
  const result = await resolveOperationalTask({ taskId: task.id, employeeId: employee.id, employeeResponse: task.resposta_funcionario, evidenceUrl: task.evidencia_url ?? null, evidenceMediaId: task.evidencia_media_id ?? null });
  await sendWhatsAppText(employee.telefone, `✅ Tarefa #${task.codigo} concluída. A confirmação foi registrada e o atendimento do cliente foi retomado automaticamente.`, message.id);
  return { ok: true, resolved: true, result };
}
async function stageEmployeeResponse(task: any, employee: Employee, message: IncomingWhatsAppMessage) {
  const supabase = getSupabaseAdmin(); const hasImage = message.type === 'image' && Boolean(message.mediaId); const incomingText = stripTaskCode(message.text); const previousText = task.resposta_funcionario?.trim() ?? '';
  if (!['text', 'image', 'interactive'].includes(message.type)) { if (employee.telefone) await sendMappedTaskText({ taskId: task.id, employeeId: employee.id, employeePhone: employee.telefone, text: `Para esta tarefa, me envie uma resposta em texto${task.requer_foto ? ' ou uma foto' : ''}. Tarefa #${task.codigo}.`, purpose: 'solicitacao', contextMessageId: message.id }); return { ok: true, unsupportedType: true }; }
  if (task.requer_foto && !hasImage) { const responseText = incomingText || previousText; const { error } = await supabase.from('tarefas_operacionais').update({ status: 'em_execucao', responsavel_id: employee.id, resposta_funcionario: responseText || null, atualizado_em: new Date().toISOString() }).eq('id', task.id); if (error) throw error; await supabase.from('tarefa_eventos').insert({ tarefa_id: task.id, ator_tipo: 'funcionario', ator_id: employee.id, evento: 'resposta_parcial', dados: { texto: responseText || null, faltaFoto: true } }); if (employee.telefone) await sendMappedTaskText({ taskId: task.id, employeeId: employee.id, employeePhone: employee.telefone, text: `Anotei a informação da tarefa #${task.codigo}. Agora falta a foto 📸. Envie a foto respondendo esta mensagem; depois eu mostro um resumo para você confirmar antes de mandar ao cliente.`, purpose: 'solicitacao', contextMessageId: message.id }); return { ok: true, waitingPhoto: true }; }
  if (hasImage && task.tipo !== 'tirar_foto' && !incomingText && !previousText) { const { error } = await supabase.from('tarefas_operacionais').update({ status: 'em_execucao', responsavel_id: employee.id, evidencia_media_id: message.mediaId, atualizado_em: new Date().toISOString() }).eq('id', task.id); if (error) throw error; if (employee.telefone) await sendMappedTaskText({ taskId: task.id, employeeId: employee.id, employeePhone: employee.telefone, text: `Foto recebida ✅. Agora escreva a confirmação em texto para a tarefa #${task.codigo} (por exemplo: “já entrou na pintura” ou “a peça ainda não chegou”). Eu não vou deduzir isso só pela imagem.`, purpose: 'solicitacao', contextMessageId: message.id }); return { ok: true, waitingText: true }; }
  const responseText = incomingText || previousText || (hasImage ? 'Foto enviada pela equipe.' : 'Confirmação enviada pela equipe.'); const evidenceMediaId = hasImage ? message.mediaId : task.evidencia_media_id ?? null; const now = new Date().toISOString();
  const { error } = await supabase.from('tarefas_operacionais').update({ status: 'aguardando_confirmacao', responsavel_id: employee.id, resposta_funcionario: responseText, evidencia_media_id: evidenceMediaId, atualizado_em: now }).eq('id', task.id); if (error) throw error;
  await supabase.from('tarefa_eventos').insert({ tarefa_id: task.id, ator_tipo: 'funcionario', ator_id: employee.id, evento: 'resposta_recebida_whatsapp', dados: { texto: responseText, mediaId: evidenceMediaId, messageId: message.id } });
  const vehicle = relationOne<any>(task.veiculos); const label = vehicle?.modelo ? `${vehicle.modelo} ${vehicle.placa}` : vehicle?.placa ?? 'veículo';
  if (employee.telefone) await sendMappedTaskText({ taskId: task.id, employeeId: employee.id, employeePhone: employee.telefone, text: [`Só confirma antes de eu mandar ao cliente — tarefa #${task.codigo}:`, `Veículo: ${label}`, `Informação: ${responseText}`, evidenceMediaId ? 'Foto: recebida ✅' : '', '', 'Responda SIM para concluir e enviar ao cliente.', 'Responda NÃO para corrigir.'].filter(Boolean).join('\n'), purpose: 'confirmacao', contextMessageId: message.id });
  return { ok: true, staged: true };
}
export async function findEmployeeByWhatsAppPhone(phone: string): Promise<Employee | null> { const normalized = normalizeWhatsAppPhone(phone); if (!normalized) return null; const supabase = getSupabaseAdmin(); const { data, error } = await supabase.from('funcionarios').select('id,nome,setor,telefone,cargo').eq('ativo', true).not('telefone', 'is', null).limit(200); if (error) throw error; return (data ?? []).find((employee: any) => normalizeWhatsAppPhone(employee.telefone ?? '') === normalized) ?? null; }
export async function processStaffWhatsAppMessage(message: IncomingWhatsAppMessage, employee: Employee) { const located = await findTaskForEmployee(message, employee); if (!located.task) { await sendAmbiguityMessage(employee, located.ambiguousIds); return { staff: true, handled: true, ambiguous: true }; } const task = located.task; if (!(await ensureTaskBelongsToEmployee(task, employee))) { if (employee.telefone) await sendWhatsAppText(employee.telefone, `Essa tarefa #${task.codigo} está atribuída a outro responsável. Para evitar atualizar o carro errado, não registrei sua resposta.`, message.id); return { staff: true, handled: true, wrongAssignee: true }; } if (located.purpose === 'confirmacao' || task.status === 'aguardando_confirmacao') return { staff: true, handled: true, ...(await confirmStagedTask(task, employee, message)) }; return { staff: true, handled: true, ...(await stageEmployeeResponse(task, employee, message)) }; }
