import 'server-only';
import { getSupabaseAdmin } from '@/lib/supabase-server';
import { sendWhatsAppText, sentWhatsAppMessageId } from '@/lib/whatsapp';

export type TaskMessagePurpose = 'solicitacao' | 'confirmacao' | 'ambiguidade';
function relationOne<T = any>(value: T | T[] | null | undefined): T | null { if (Array.isArray(value)) return value[0] ?? null; return value ?? null; }
async function recordOutboundTaskMessage(input: { taskId: string; employeeId: string; messageId: string; purpose: TaskMessagePurpose }) { if (!input.messageId) return; const supabase = getSupabaseAdmin(); const { error } = await supabase.from('tarefa_mensagens_whatsapp').insert({ tarefa_id: input.taskId, funcionario_id: input.employeeId, message_id: input.messageId, direcao: 'sistema_para_funcionario', finalidade: input.purpose }); if (error?.code !== '23505' && error) throw error; }
export async function sendMappedTaskText(input: { taskId: string; employeeId: string; employeePhone: string; text: string; purpose: TaskMessagePurpose; contextMessageId?: string }) { const response = await sendWhatsAppText(input.employeePhone, input.text, input.contextMessageId); const messageId = sentWhatsAppMessageId(response); await recordOutboundTaskMessage({ taskId: input.taskId, employeeId: input.employeeId, messageId, purpose: input.purpose }); return { response, messageId }; }
async function sectorHasSingleActiveEmployee(sector: string | null, assignedEmployeeId: string) { if (!sector?.trim()) return true; const supabase = getSupabaseAdmin(); const { data, error } = await supabase.from('funcionarios').select('id').eq('ativo', true).ilike('setor', sector.trim()).limit(2); if (error) throw error; return data?.length === 1 && data[0].id === assignedEmployeeId; }
export async function sendOperationalTaskToEmployee(taskId: string) {
  const supabase = getSupabaseAdmin(); const { data: task, error } = await supabase.from('tarefas_operacionais').select('id,codigo,tipo,titulo,instrucoes,setor_responsavel,responsavel_id,prioridade,requer_foto,origem_mensagem,veiculos(id,placa,modelo),funcionarios(id,nome,setor,telefone)').eq('id', taskId).single(); if (error) throw error; if (!task) return { sent: false, reason: 'task_not_found' as const };
  const employee = relationOne<any>(task.funcionarios); const vehicle = relationOne<any>(task.veiculos); if (!employee?.id || !employee?.telefone) return { sent: false, reason: 'employee_without_whatsapp' as const };
  if (!(await sectorHasSingleActiveEmployee(task.setor_responsavel, employee.id))) return { sent: false, reason: 'ambiguous_sector_assignment' as const };
  const vehicleLabel = vehicle?.modelo ? `${vehicle.modelo} — ${vehicle.placa}` : vehicle?.placa || 'veículo não identificado'; const priority = task.prioridade === 'urgente' ? '🚨 URGENTE' : task.prioridade === 'alta' ? '⚠️ PRIORIDADE ALTA' : '🔧 Nova tarefa'; const customerQuestion = String(task.origem_mensagem ?? '').trim().slice(0, 500);
  const text = [`${priority} #${task.codigo}`, `Veículo: ${vehicleLabel}`, task.setor_responsavel ? `Setor: ${task.setor_responsavel}` : '', customerQuestion ? `Cliente perguntou: “${customerQuestion}”` : '', '', `Preciso que você: ${task.instrucoes}`, task.requer_foto ? '📸 Esta tarefa precisa de foto.' : '', '', 'Responda ESTA mensagem com a informação solicitada' + (task.requer_foto ? ' e a foto.' : '.'), `Se mandar uma mensagem solta, escreva #${task.codigo} para eu saber de qual veículo é.`, 'Eu vou confirmar com você antes de enviar qualquer coisa ao cliente.'].filter(Boolean).join('\n');
  const result = await sendMappedTaskText({ taskId: task.id, employeeId: employee.id, employeePhone: employee.telefone, text, purpose: 'solicitacao' });
  await supabase.from('tarefa_eventos').insert({ tarefa_id: task.id, ator_tipo: 'sistema', evento: 'whatsapp_funcionario_enviado', dados: { funcionarioId: employee.id, messageId: result.messageId } });
  return { sent: true, messageId: result.messageId, employeeId: employee.id };
}
export async function findTaskIdByOutboundMessage(messageId: string) { if (!messageId) return null; const supabase = getSupabaseAdmin(); const { data, error } = await supabase.from('tarefa_mensagens_whatsapp').select('tarefa_id,funcionario_id,finalidade').eq('message_id', messageId).maybeSingle(); if (error) throw error; return data ?? null; }
